services:
  - name: backend
    type: web
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - name: frontend
    type: web
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
